name: two jobs

on: 
  push:
        branches:
          - feature_new
  workflow_dispatch:
  schedule:
      - cron: '0/45 * 2-5 * *'


jobs:
        job01:
                name: Job Linux
                runs-on: ubuntu-latest
                steps:
                        - name: Etapa 01
                          uses: actions/checkout@v3
                        - name: Etapa 02
                          run: |
                                  echo "$(cat README.md)"
                                  uname -a
        job02:
                name: Job Windows
                runs-on: windows-latest
                steps:
                        - name: Etapa 01
                          uses: actions/checkout@v3
                        - name: Etapa 02
                          run: "Get-CimInstance Win32_OperatingSystem"
