name: two jobs

on: push

jobs:
        jobLinux:
                name: Job 01
                runs-on: ubuntu-latest
                steps:
                        - name: Etapa 01
                          uses: actions/checkout@v3
                        - name: Etapa 02
                          run: |
                                  echo "$(cat README.md)"
                                  uname -a
        jobWindows:
                name: Job 02
                runs-on: windows-latest
                steps:
                        - name: Etapa 01
                          uses: actions/checkout@v3
                        - name: Etapa 02
                          run: "Get-CimInstance Win32_OperatingSystem"